# GitHub Actions for AudioKitUI
name: CI

on: [push, pull_request]
env:
  XCODE_VER: latest-stable

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['13.2']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out AudioKitUI
        uses: actions/checkout@v2
      - name: Build AudioKitUI
        run: |
          set -euo pipefail
          swift package clean
          swift build --sanitize="address"
